### ISSUE TITLE
Mob EVADE

### ISSUE THREAD

**Issue by atidot3** [ZhengPeiRu21/mod-playerbots#93] opened 2022-07-28 11:44 UTC
Hii,

I've noticed the mob enter evade phase if you attack them from distance (like a warlock).

after few miss the mob enter evade phase, go back to spawn and is not attackable anymore until a server restart.
i've been trying out alot of test but nothing seems to be functionnal, either launched in Windows and Linux same result.

What surpise me is with a melee it is working fine.

**Comment by Grakazela** [comment] 2022-07-29 02:29
+1.
running on ubuntu 18.04
most recent version of azerothcore, fork and module, mobs evade when attacked from range, occasionally stop pathfinding and evade until server restart. gm command .die then waiting to respawn does not fix. caster mobs will evade after first hit, cast 2-3 times then evade bug from ranged or melee, removed module and still compiled with fork, same issue. currently doing fresh azerothcore compile with no module to see if issue persists

edit: compiled with no module, and base azerothcore. sql edits still in place, mobs working properly again. issue seems to be with the fork, not the module itself

**Comment by atidot3** [comment] 2022-07-29 03:14
Using main branch azeroth core (not playerbot) is working as intended.

**Comment by flekz-games** [comment] 2022-08-03 08:37
I am getting the same issues here on ubuntu 20.04 building latest on the Playerbot fork and the latest module version. Everytime the bots are near a player the attacked npc bugs out and can't be hit by any means, always evading.

@atidot3 @Grakazela  Just to clarify. Did you build on the latest azerothcore branch from https://github.com/azerothcore/azerothcore-wotlk or from https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/master and with or without the playerbot module?

**Comment by atidot3** [comment] 2022-08-03 09:03
Hi,

i somesort of fixed this issue with reverting must changes on the core related to the <SetCannotReachTarget> function.
You can try it by pulling my fork available here:
https://github.com/atidot3/azerothcore-wotlk

Commit:
https://github.com/atidot3/azerothcore-wotlk/commit/da0e01eea41d600c83dc859d13aa3e906300faf6

I havent really made much more testing yet.


As it is related to the core with or without the module doesnt matter.
Branch used:  https://github.com/ZhengPeiRu21/azerothcore-wotlk/tree/master

**Comment by flekz-games** [comment] 2022-08-03 09:18
Thanks so much atidot3. Taking a look at the diff from your change, did you just change the files from the core or also the files inside of the module?

**Comment by atidot3** [comment] 2022-08-03 09:27
Only on the core, the module is a submodule from:
[submodule "modules/mod-playerbots"]
	path = modules/mod-playerbots
	url = https://github.com/ZhengPeiRu21/mod-playerbots.git

**Comment by flekz-games** [comment] 2022-08-03 10:35
For a future reference if @ZhengPeiRu21 decides to tackle this issue. The issue seems to come from the Unit::SetCannotReachTarget, probably being called from somewhere in TargetedMovementGenerator and hanging up the combat. I do not know how to debug a build so I cannot help any further. Sorry...

**Comment by Grakazela** [comment] 2022-08-03 20:14
@davidonete i did a fresh pull from the github, didnt grab the fork, and didnt have the module. so only the sql edits remained and the server is running.

**Comment by Deathman182** [comment] 2022-08-09 09:20
I have a clone of his core repo from 06/2022 everything was working back than - must have been some recent change that kills the combat

**Comment by ZhengPeiRu21** [comment] 2022-08-10 22:57
Sorry for the slow responding on this issue! I think I have find the problem and will have it fixed in the next few days. Thank you for the detailed reporting and helpful comments.

**Comment by ZhengPeiRu21** [comment] 2022-08-18 19:49
Would someone when convenient please test if my latest commits to the Playerbot Azerothcore fork fix this problem?

**Comment by heyitsbench** [comment] 2022-08-18 21:11
> Would someone when convenient please test if my latest commits to the Playerbot Azerothcore fork fix this problem?

Getting the following build error on both latest AC-playerbot branch and Playerbot module:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2065	'm_speakTime': undeclared identifier	game	C:\Users\benjy\Documents\GitHub\acplayerbots\azerothcore-wotlk\src\server\game\Entities\Player\Player.cpp	15977	
Error	C2065	'm_speakCount': undeclared identifier	game	C:\Users\benjy\Documents\GitHub\acplayerbots\azerothcore-wotlk\src\server\game\Entities\Player\Player.cpp	15978	
Error	LNK1181	cannot open input file '..\game\RelWithDebInfo\game.lib'	worldserver	C:\Users\benjy\Documents\GitHub\acplayerbots\acbuild\src\server\apps\LINK	1	
```

**Comment by ZhengPeiRu21** [comment] 2022-08-19 16:05
> > Would someone when convenient please test if my latest commits to the Playerbot Azerothcore fork fix this problem?
> 
> Getting the following build error on both latest AC-playerbot branch and Playerbot module:
> 
> ```
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	C2065	'm_speakTime': undeclared identifier	game	C:\Users\benjy\Documents\GitHub\acplayerbots\azerothcore-wotlk\src\server\game\Entities\Player\Player.cpp	15977	
> Error	C2065	'm_speakCount': undeclared identifier	game	C:\Users\benjy\Documents\GitHub\acplayerbots\azerothcore-wotlk\src\server\game\Entities\Player\Player.cpp	15978	
> Error	LNK1181	cannot open input file '..\game\RelWithDebInfo\game.lib'	worldserver	C:\Users\benjy\Documents\GitHub\acplayerbots\acbuild\src\server\apps\LINK	1	
> ```

Thank you. I am strange this did not see when doing my own local build. I will create a fix.

**Comment by ZhengPeiRu21** [comment] 2022-08-19 18:17
It looks like the error was from an unrelated upstream change. I've updated both the module and the branch. Please test again when is convenient. Thank you!

**Comment by heyitsbench** [comment] 2022-08-19 18:41
The issue still happens, but it is *very* infrequent for the player character in my testing. However, it seems to still be happening on basically every mob for the player bots.
It's still uploading right now, but here's a video of a bit of my testing showing the bots getting hung up: https://www.youtube.com/watch?v=bLIY9eEE_9U

**Comment by ZhengPeiRu21** [comment] 2022-08-20 02:38
Thank you again for retesting. I will take another look at the fix.

**Comment by OpexNSK** [comment] 2022-08-29 09:22
The issue still happens.

**Comment by rogerc66** [comment] 2022-08-31 13:12
> The issue still happens.

confirmed, still happens

**Comment by ZhengPeiRu21** [comment] 2022-09-06 23:40
Thank you for the reports. I have try another attempt at fix the issue. Please let me know if it appears to be resolve!

**Comment by OpexNSK** [comment] 2022-09-07 06:10
I checked the new build, the npc are not avoiding in combat. But!!! My bots(not random) do not respond to commands, they respond to everything in the chat (unknown command ****). Only following works.  
When I turn on random bots I get crash:  https://github.com/ZhengPeiRu21/mod-playerbots/issues/96

**Comment by ZhengPeiRu21** [comment] 2022-09-07 15:18
> I checked the new build, the npc are not avoiding in combat. But!!! My bots(not random) do not respond to commands, they respond to everything in the chat (unknown command ****). Only following works. When I turn on random bots I get crash: #96

Thank you so much for testing! I think we have fixed the evade issue which was the large blocking problem. I will continue to look at the other issues.

**Closed as completed by ZhengPeiRu21** 2022-09-07 15:18 UTC

**Comment by cocely** [comment] 2022-12-07 03:50
nice
