### ISSUE TITLE
Segment fault core dumped

### ISSUE THREAD

**Issue by rogerc66** [ZhengPeiRu21/mod-playerbots#36] opened 2022-04-07 06:25 UTC
I left my server running for over 26 hrs and it crashed with `Segment fault, Core dumped` error.

I found there is no error log in server directory, I guess it might be an outcome of out of memory of my virtual machine since Playerbots took ton of memory to running good, although I have assigned 4G of memory plus 5G of swap, but the performance still not rubust enough to support 100 bots simultaneously. anyone else have any idea to optimize? or I have to upgrade hardware to assign more memory to virtual machine.

Thank you.

**Comment by ZhengPeiRu21** [comment] 2022-04-07 14:51
If it is crash because of a seg fault, it is probably a code error somewhere, not a memory issue. We are still finding causes for all crashes but it is much improving! 26 hrs is quite a good up time. If you are able to share the crash message, it can help find the cause and have it fixed.

If you do want to improve memory issue, you can reduce percentage of active bots, or disable some systems like Guild Tasks.

**Comment by Greyisttot** [comment] 2022-04-07 19:05
I have a 4CPU core and 16GB memory. I have 2000 robots online. The CPU usage is 20% and the memory usage is 40%, but the processing is very slow. The movements of the game to the robot including the creatures are slow. I don't know if it is the disk IO read write and question.

**Comment by Bogir** [comment] 2022-04-08 14:50
I've noticed that bots are stopped after each action to 10-20 seconds. Maybe they are thinking about something? :)

**Comment by rogerc66** [comment] 2022-04-26 01:52
> I've noticed that bots are stopped after each action to 10-20 seconds. Maybe they are thinking about something? :)

They are thinking what to eat tonight for dinner. ;D

**Comment by htc16** [comment] 2022-04-26 02:11
it was definitely memory failure, in my opinion you need at least 8GB of RAM.
L

**Comment by godlike73** [comment] 2022-07-02 05:29
On a linux build cant get the server to stay up more then a few seconds minutes at most with a core dump... Disable playerbot stays up for days

**Comment by ZhengPeiRu21** [comment] 2022-09-23 20:10
I am going to close this issue because it is too general to resolve. Please feel free to open a new issue with details if come across another seg fault.

**Closed as completed by ZhengPeiRu21** 2022-09-23 20:10 UTC
